[project]
name = "sensible-types"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "pyright>=1.1.388",
    "pytest>=8.3.3",
    "ruff>=0.7.3",
]

[tool.ruff]
line-length=100
